### ISSUE TITLE
Move screenshot cropping outside PhantomJS

### ISSUE THREAD

**Issue by lazytesting** [arguseyes/argus-eyes#10]
Currently the screenshots are cropped within PhantomJS. The capture process will be a lot faster if we take a screenshot of the whole viewport and crop the image with another tool.

**Comment by branneman** [comment]
Agreed! [pngjs-image](https://www.npmjs.com/package/pngjs-image) will be perfect for the job.

**Comment by branneman** [comment]
This has landed in `dev`, and will be released with v0.5.0.
