### ISSUE TITLE
Feature: running screenshots parallel

### ISSUE THREAD

**Issue by cstegeman** [arguseyes/argus-eyes#11]
As I am currently working on a repository with around 500 templates/components, it's very handy to speedup the process. 

Is it possible to add the option to configure the amount of instances which can be run simultaneously?

**Comment by branneman** [comment]
Agreed. This will be done in 2 steps:

1. Move cropping outside of PhantomJS, so every PhantomJS instance makes a single screenshot per page. Then multiple crops can be done without starting the same amount of PhantomJS instances. See #10
2. Run a pool of PhantomJS instances with a sane (and configurable) concurrency limit. This way the more memory and processing power you have, to more you can parallelize.

**Comment by cstegeman** [comment]
Great! Can't wait :D

**Comment by branneman** [comment]
The cropping has been moved out of PhantomJS, this will land in v0.5.0.

Soon™

**Comment by cstegeman** [comment]
Cool, thanks for the update!

**Comment by branneman** [comment]
6b385c5 added the running multiple PhantomJS instances in parallel, up to the concurrency limit. Will also land in v0.5.0.
