### ISSUE TITLE
Phantom Flags

### ISSUE THREAD

**Issue by camjc** [arguseyes/argus-eyes#15]
Hey,
Is there any way to pass phantomJS config flags through?
I need to turn off ssl for my dev environment.

Thanks for the tool,
- Cameron

**Comment by branneman** [comment]
Right now, thats not possible. This is a great idea for a feature though, we'll put it on the list!

**Comment by branneman** [comment]
This has been added in [Argus Eyes v0.6.0](https://github.com/arguseyes/argus-eyes/releases/tag/v0.6.0), closing this issue as resolved.
