### ISSUE TITLE
hi, how does this tools set cookies ?

### ISSUE THREAD

**Issue by qileilove** [arguseyes/argus-eyes#17]
hi,the website need to login, if i want diff other page, it need to set cookies,How can I deal with this problem？

**Comment by branneman** [comment]
Hey @qileilove,

What kind of authentication mechanism do you have?

If we're talking about HTTP Basic Authentication, you can specify the credentials in your config file. See the docs:
- http://arguseyes.io/reference.html#credentials

If we're talking about manually setting cookies after page load, this is possible with the `run-script` option. See docs:
- http://arguseyes.io/reference.html#run-script

If we're talking about having cookies available before the http request is sent, you should take a look at passing a custom cookies files to PhantomJS. See docs:
- http://arguseyes.io/reference.html#phantomjs-flags
- http://arguseyes.io/reference.html#phantomjs-flags

Please let us know if you need anything else. I'm closing this issue as a question.

**Comment by qileilove** [comment]
@branneman Thanks.
I think we're talking about having cookies available before the http request is sent.
{ "phantomjs-flags": ["--load-images=false"] }


` --cookies-file=/path/to/cookies.txt `

specifies the file name to store the persistent Cookies.

so I need to config the json conf file with `{ "phantomjs-flags": [" --cookies-file=/path/to/cookies.txt"]}`

I'll try it. thanks again.
