### ISSUE TITLE
Avoiding false negatives with comparing

### ISSUE THREAD

**Issue by rarkins** [arguseyes/argus-eyes#19]
I'm having a bad experience with the `compare` function continuously returning a false negative on a particularly "search bar" on my site. It's flagged as changed on most commits, just off by a slight amount and anywhere from 0.08% - 1.27% so far. In actual fact the location of this search bar doesn't change at all, so something is causing PhantomJS to put it in "random" places somehow.

Example diff:
![image](https://cloud.githubusercontent.com/assets/6311784/16793298/32d24fb4-48d0-11e6-8185-4560c3626e15.png)
(Please ignore the badly placed text below that - not relevant to this)

I would really prefer not to have to set threshold to 1.5% "globally" because in many cases that might be an amount of change somewhere that is a true negative rather than a false negative. I also would prefer not to exclude this element from the capture because it is important to the page (first thing you see on the home page..)

So the alternative would seem to be: "understand why PhantomJS is showing it in slightly different locations eery time". Do you have any experience or advice on this?

By the way I'm assuming it's PhantomJS's fault and not blink-diff.

**Comment by branneman** [comment]
Have you already tried any of the `wait-for-delay` or `wait-for-script` options to delay taking a screenshot until your page is fully ready?

Also, are you taking a screenshot of the entire page, or using component-specific selectors? Just screenshotting that single "search bar" component might solve your problem as well.

If you paste a (shortened) version of your config file (`argus-eyes.json`) we could take a look at it.

**Comment by rarkins** [comment]
Hi @branneman, thanks for the quick response.

I'm testing it out using `wait-for-delay` and I think it may be doing the trick - I'll close this once I am sure of it.

FYI I am/was capturing just a specific selector and not the whole page. It wasn't really useful to capture only that search bar nor to exclude it either - its positioning on the page was important, but somehow it kept "jittering" its location with every capture.

**Comment by rarkins** [comment]
Confirming that adding the `wait-for-delay` setting solved this image capture "jitter" problem. Thanks.
