### ISSUE TITLE
Allow comparison threshold to be configurable per-component

### ISSUE THREAD

**Issue by rarkins** [arguseyes/argus-eyes#21]
Currently the threshold parameter is a command-line one, and so applies to the entire compare. For example if I have 50 different components I'm capturing and just one of them has a regular 1% diff (to ignore), then it means I need to allow for a 1%+ difference for the other 49 captures too, which is undesirable.

Ideally this could be configured in a cascading global-page-component manner like is supported for options like `wait-for-delay`.

**Comment by branneman** [comment]
Interesting idea, not sure if it fits together with the [ignore selector](http://arguseyes.io/reference.html) feature. What is the nature of the difference, and why wouldn't the ignore feature solve your problem?

@lazytesting what do you think of it?

**Comment by rarkins** [comment]
But then by the same logic would imply you *never* need a threshold function? I don't understand how it can be considered useful globally but not per-component. Nor how it conflicts with the option to hide certain selectors.  

I would prefer to set a threshold per/component rather than ignore selectors completely. In some cases we still want to check that something is displaying and in the correct position, even if the content may itself change.

**Comment by lazytesting** [comment]
@rarkins you have a point, it makes sense to be able to set this on component level. 
Let's make it configurable on the following levels:
- base config
- page 
- component

If it's  set on multiple levels we use the highest value. This allows you to set a base threshold and use a higher value on a specific page or component. 

With this change we should remove the CLI option, as the CLI arguments should be used for environment specific settings only.
