### ISSUE TITLE
finished-when is useless

### ISSUE THREAD

**Issue by withinboredom** [arguseyes/argus-eyes#5]
The current method only gives 20 tries every couple hundred milliseconds. This is useless when you may need to wait tens of seconds for content on the page to be loaded before capturing.

**Comment by branneman** [comment]
Correct, at this moment argus-eyes does not support pages that take that long to load. The exact timeout by the way is 2 seconds after the `document.readyState === 'complete'`.

Could you elaborate on your use case?

**Comment by withinboredom** [comment]
2 seconds is plenty of time in my use case (I was originally trying to wait 5). Thanks for building this btw!

**Comment by branneman** [comment]
Ah ok, I'm closing this issue as a discussion issue, but feel free to continue discussion here.

**Comment by branneman** [comment]
FYI: The timeout has just been increased to 5 seconds after `DOMContentLoaded`, see commit 7c3a78f5e07a5ce4e074f9121a9129c1563a00be for implementation. This will be available next release.
